lenguaje: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - krlosaren@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: 'Deploy Success'
  on:
    branch: master